<div id="slider-smartlinks" class="block slideshow noscript">

	<script data-cfasync="false" type="text/javascript">var lsjQuery = jQuery;</script>
	<script data-cfasync="false" type="text/javascript">
		lsjQuery(document).ready(function() {
			if(typeof lsjQuery.fn.layerSlider == "undefined") { lsShowNotice('layerslider_1','jquery'); }
			else {
				lsjQuery("#layerslider_1").layerSlider({responsive: false, responsiveUnder: 1280, layersContainer: 1280, startInViewport: false, skin: 'noskin', globalBGColor: '#f0f4f7', hoverPrevNext: false, lazyLoad: false, yourLogoStyle: 'left: 10px; top: 10px;', cbInit: function(element) { }, cbStart: function(data) { }, cbStop: function(data) { }, cbPause: function(data) { }, cbAnimStart: function(data) { }, cbAnimStop: function(data) { }, cbPrev: function(data) { }, cbNext: function(data) { }, skinsPath: 'http://smartlinks.vn/wp-content/plugins/LayerSlider/static/skins/'})
			}
		});
	</script>

	<div id="layerslider_1" class="ls-wp-container" style="width:100%;height:470px;margin:0 auto;margin-bottom: 0px;">

		<div class="ls-slide" data-ls="slidedelay:7000;transition2d:5;">
			<img class="ls-l" style="top:-120px;left:50%;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:120;durationin:3500;easingin:easeOutQuad;offsetxout:0;durationout:4000;easingout:easeInExpo;scalexout:2;scaleyout:2;parallaxlevel:-2;" src="resources/assets/smartlinks/2016/01/slider_background_1.jpg" alt="">
			<img class="ls-l" style="top:-490px;left:50%;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:490;durationin:3600;easingin:easeOutQuad;offsetxout:0;durationout:4000;easingout:easeInExpo;scalexout:2.5;scaleyout:2.5;parallaxlevel:-1;" src="resources/assets/smartlinks/2016/01/stars-parallax1.png" alt="">
			<img class="ls-l" style="top:-900px;left:75%;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:1800;durationin:1300;delayin:1000;easingin:linear;fadein:false;scalexin:2;scaleyin:1.5;offsetxout:0;durationout:0;fadeout:false;" src="resources/assets/smartlinks/2016/01/star-big-parallax11.png" alt="">
			<img class="ls-l" style="top:-900px;left:25%;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:1800;delayin:1800;easingin:linear;fadein:false;scalexin:5;scaleyin:4;offsetxout:0;durationout:0;fadeout:false;" src="resources/assets/smartlinks/2016/01/star-big-parallax11.png" alt="">
			<p class="ls-l" style="top:360px;left:50%;width:530px;height:530px;background:#FFAF70;border-radius:265px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:300;durationin:4000;delayin:300;easingin:easeOutQuad;fadein:false;offsetxout:0;offsetyout:100px;durationout:4000;easingout:easeInExpo;scalexout:3;scaleyout:3;parallaxlevel:1;"></p>
			<div class="ls-l star1_orbit" style="top:625px;left:50%;width:5px;height:5px;background:#ffffff;border-radius:3px;white-space: nowrap;" data-ls="offsetxin:0;delayin:2000;easingin:linear;"></div>
			<div class="ls-l star2_orbit" style="top:625px;left:50%;width:22px;height:22px;background:#48afdb;border-radius:11px;white-space: nowrap;" data-ls="offsetxin:0;delayin:2000;easingin:linear;"></div>
			<div class="ls-l star3_orbit" style="top:625px;left:50%;width:11px;height:11px;background:#60dbc4;border-radius:6px;white-space: nowrap;" data-ls="offsetxin:0;delayin:2000;easingin:linear;"></div>
			<div class="ls-l star4_orbit" style="top:625px;left:50%;width:10px;height:10px;background:#ffffff;border-radius:5px;white-space: nowrap;" data-ls="offsetxin:0;delayin:2000;easingin:linear;"></div>
			<div class="ls-l star5_orbit" style="top:625px;left:50%;width:15px;height:15px;background:#48afdb;border-radius:7px;white-space: nowrap;" data-ls="offsetxin:0;delayin:2000;easingin:linear;"></div>
			<div class="ls-l star6_orbit" style="top:625px;left:50%;width:16px;height:16px;background:#48afdb;border-radius:8px;white-space: nowrap;" data-ls="offsetxin:0;delayin:2000;easingin:linear;"></div>
			<div class="ls-l star7_orbit" style="top:625px;left:50%;width:6px;height:6px;background:#60dbc4;border-radius:3px;white-space: nowrap;" data-ls="offsetxin:0;delayin:2000;easingin:linear;"></div>
			<div class="ls-l star8_orbit" style="top:625px;left:50%;width:13px;height:13px;background:#60dbc4;border-radius:7px;white-space: nowrap;" data-ls="offsetxin:0;delayin:2000;easingin:linear;"></div>
			<div class="ls-l" style="top:133px;left:170px;font-family:helveticaneueultralight;font-size:85px;line-height:115px;color:#ffffff;white-space: nowrap;" data-ls="offsetxin:left;offsetyin:top;delayin:1500;easingin:easeOutQuart;rotatein:-100;transformoriginin:0% 50% 0;offsetxout:left;offsetyout:top;durationout:1000;easingout:easeInExpo;rotateout:-30;scalexout:6;scaleyout:6;parallaxlevel:3;">Welcome</div>
			<div class="ls-l" style="top:132px;left:521px;font-family:helveticaneueultralight;font-size:85px;line-height:115px;color:#ffffff;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:top;durationin:1400;delayin:1800;easingin:easeOutQuart;rotatein:30;offsetxout:0;offsetyout:top;durationout:1000;easingout:easeInExpo;scalexout:6;scaleyout:6;parallaxlevel:3;">to</div>
			<div class="ls-l" style="top:123px;left:616px;font-family:helveticaneueultralight;font-size:85px;line-height:115px;color:#ffffff;white-space: nowrap;" data-ls="offsetxin:right;offsetyin:top;durationin:1300;delayin:2300;easingin:easeOutQuart;rotatein:150;offsetxout:right;offsetyout:top;durationout:1000;easingout:easeInExpo;rotateout:30;scalexout:6;scaleyout:6;parallaxlevel:3;"><span style="color: #71dfca; background-color: rgba(0, 0, 0, 0.6);padding: 0 20px;">SMARTLINKS</span>
			</div>
			<div class="ls-l" style="top:236px;left:342px;text-align: center;font-family:helveticaneueultralight;font-size:30px;line-height:40px;color:#ffffff;" data-ls="offsetxin:left;durationin:2000;delayin:2600;easingin:easeOutQuart;rotatein:-100;offsetxout:-500;offsetyout:-350;durationout:1000;easingout:easeInExpo;rotateout:-30;scalexout:3;scaleyout:3;parallaxlevel:2;">Đem Lại <span style="color: #48afdb;">Lợi Nhuận</span> Và Sự Hài Lòng</div>
			<div class="ls-l" style="top:238px;left:791px;text-align: center;font-family:helveticaneueultralight;font-size:30px;line-height:40px;color:#ffffff;" data-ls="offsetxin:right;durationin:2000;delayin:2800;easingin:easeOutQuart;rotatein:100;offsetxout:500;offsetyout:-350;durationout:1000;easingout:easeInExpo;rotateout:30;scalexout:3.5;scaleyout:3.5;parallaxlevel:2;">Cho Khách Hàng </div>
			<div class="ls-l" style="top:284px;left:467px;text-align: center;font-family:helveticaneueultralight;font-size:30px;line-height:40px;color:#ffffff;" data-ls="offsetxin:left;offsetyin:bottom;durationin:2500;delayin:3000;easingin:easeOutQuart;rotatein:100;offsetxout:-550;offsetyout:-120;durationout:1000;easingout:easeInExpo;rotateout:-10;scalexout:3.5;scaleyout:3.5;parallaxlevel:2;"><span style="color: #71dfca;">Luôn Là Mục Tiêu</span> Của Chúng Tôi</div>
		</div>


		<div class="ls-slide" data-ls="slidedelay:5000;transition2d:104;">
			<img class="ls-l" style="top:0px;left:50%;white-space: nowrap;" data-ls="offsetxin:0;durationin:2000;easingin:easeInQuart;offsetxout:0;durationout:1000;easingout:easeInQuart;" src="resources/assets/smartlinks/2016/01/slider_background_2.jpg" alt="">
			<img class="ls-l" style="top:-63px;left:680px;white-space: nowrap;" data-ls="offsetxin:right;durationin:1500;delayin:1000;easingin:easeOutQuart;rotatein:100;offsetxout:left;durationout:2000;easingout:easeInQuart;rotateout:-120;parallaxlevel:3;" src="resources/assets/smartlinks/2016/01/tem_google_partner1.png" alt="">
			<img class="ls-l" style="top:-69px;left:232px;white-space: nowrap;" data-ls="offsetxin:right;durationin:1700;delayin:900;easingin:easeOutQuart;rotatein:90;offsetxout:left;durationout:500;easingout:easeInQuart;rotateout:-90;parallaxlevel:7;" src="resources/assets/smartlinks/2016/01/marka2.png" alt="">
			<img class="ls-l" style="top:230px;left:1147px;white-space: nowrap;" data-ls="offsetxin:right;durationin:2000;delayin:1000;easingin:easeOutQuart;rotatein:320;offsetxout:left;durationout:2500;easingout:easeInQuart;rotateout:-360;parallaxlevel:1;" src="resources/assets/smartlinks/2016/01/marka1.png" alt="">
			<div class="ls-l" style="top:255px;left:650px;width:17px;height:17px;background:#48afdb;border-radius:10px;white-space: nowrap;" data-ls="offsetxin:right;durationin:1200;delayin:1100;easingin:easeOutQuart;offsetxout:-600;durationout:1000;easingout:easeInQuart;parallaxlevel:4;"></div>
			<div class="ls-l" style="top:370px;left:1115px;width:10px;height:10px;background:#48afdb;border-radius:7px;white-space: nowrap;" data-ls="offsetxin:right;durationin:1200;delayin:1200;easingin:easeOutQuart;offsetxout:-700;durationout:1000;easingout:easeInQuart;parallaxlevel:3;"></div>
			<div class="ls-l" style="top:440px;left:1175px;width:4px;height:4px;border-top:1px solid #3b3e4f;;border-right:1px solid #3b3e4f;;border-bottom:1px solid #3b3e4f;;border-left:1px solid #3b3e4f;;border-radius:7px;white-space: nowrap;" data-ls="offsetxin:right;durationin:1200;delayin:1300;easingin:easeOutQuart;offsetxout:-800;durationout:1000;easingout:easeInQuart;parallaxlevel:1;"></div>
			<div class="ls-l" style="top:440px;left:720px;width:12px;height:12px;border-top:1px solid #3b3e4f;;border-right:1px solid #3b3e4f;;border-bottom:1px solid #3b3e4f;;border-left:1px solid #3b3e4f;;border-radius:7px;white-space: nowrap;" data-ls="offsetxin:right;durationin:1200;delayin:1400;easingin:easeOutQuart;offsetxout:-900;durationout:1000;easingout:easeInQuart;parallaxlevel:2;"></div>
			<div class="ls-l" style="top:290px;left:610px;width:6px;height:6px;border-top:1px solid #3b3e4f;;border-right:1px solid #3b3e4f;;border-bottom:1px solid #3b3e4f;;border-left:1px solid #3b3e4f;;border-radius:10px;white-space: nowrap;" data-ls="offsetxin:right;durationin:1200;delayin:1500;easingin:easeOutQuart;offsetxout:-1000;durationout:1000;easingout:easeInQuart;parallaxlevel:1;"></div>
			<div class="ls-l" style="top:35px;left:710px;width:26px;height:26px;border-top:1px solid #48afdb;;border-right:1px solid #48afdb;;border-bottom:1px solid #48afdb;;border-left:1px solid #48afdb;;border-radius:15px;white-space: nowrap;" data-ls="offsetxin:right;durationin:1200;delayin:1600;easingin:easeOutQuart;offsetxout:-700;durationout:1000;easingout:easeInQuart;parallaxlevel:10;"></div>
			<div class="ls-l" style="top:112px;left:47px;font-family:helveticaneueultralight;font-size:83px;line-height:115px;color:#6597fe;white-space: nowrap;" data-ls="offsetxin:680;offsetyin:-80;durationin:1500;delayin:600;easingin:easeOutQuart;rotatein:90;scalexin:0.1;scaleyin:0.1;offsetxout:left;durationout:700;easingout:easeInQuart;rotateout:-45;parallaxlevel:-3;">Đối Tác Chính Thức</div>
			<div class="ls-l" style="top:210px;left:47px;font-family:helveticaneueultralight;font-size:83px;line-height:115px;color:#48afdb;white-space: nowrap;" data-ls="offsetxin:580;offsetyin:-80;durationin:1500;delayin:700;easingin:easeOutQuart;rotatein:80;scalexin:0.1;scaleyin:0.1;offsetxout:left;durationout:700;easingout:easeInQuart;rotateout:-30;parallaxlevel:-2;">Của Google</div>
			<div class="ls-l" style="top:343px;left:54px;font-family:helveticaneueultralight;font-size:30px;line-height:40px;color:#3b3e4f;white-space: nowrap;" data-ls="offsetxin:480;offsetyin:-80;durationin:1500;delayin:800;easingin:easeOutQuart;rotatein:70;scalexin:0.1;scaleyin:0.1;offsetxout:left;durationout:700;easingout:easeInQuart;rotateout:-20;parallaxlevel:-1;">Triển Khai Hơn 2000 Chiến Dịch</div>
			<div class="ls-l" style="top:383px;left:54px;font-family:helveticaneueultralight;font-size:30px;line-height:40px;color:#3b3e4f;white-space: nowrap;" data-ls="offsetxin:380;offsetyin:-80;durationin:1500;delayin:900;easingin:easeOutQuart;rotatein:60;scalexin:0.1;scaleyin:0.1;offsetxout:left;durationout:700;easingout:easeInQuart;rotateout:-10;parallaxlevel:-1;">Hơn 1000 Khách Hàng Thân Thiết</div>
		</div>


		<div class="ls-slide" data-ls="slidedelay:5500;timeshift:500; transition2d: all;">
			<img class="ls-l" style="top:50%;left:50%;white-space: nowrap;" data-ls="offsetxin:0;durationin:1500;easingin:easeInOutSine;offsetxout:0;durationout:1500;easingout:easeInOutSine;" src="resources/assets/smartlinks/2016/01/slider_background_5.jpg" alt="">
			<div class="ls-l" style="top:15px;left:810px;width:13px;height:13px;background:#60dbc4;border-radius:15px;white-space: nowrap;" data-ls="offsetxin:-10;offsetyin:top;durationin:600;delayin:1000;easingin:easeOutQuart;offsetxout:left;easingout:easeInQuart;parallaxlevel:-5;"></div>
			<div class="ls-l" style="top:300px;left:925px;width:8px;height:8px;background:#60dbc4;border-radius:15px;white-space: nowrap;" data-ls="offsetxin:-30;offsetyin:bottom;durationin:700;delayin:1100;easingin:easeOutQuart;offsetxout:left;easingout:easeInQuart;parallaxlevel:2;"></div>
			<div class="ls-l" style="top:383px;left:1133px;width:4px;height:4px;border-top:1px solid #fff;;border-right:1px solid #fff;;border-bottom:1px solid #fff;;border-left:1px solid #fff;;border-radius:15px;white-space: nowrap;" data-ls="offsetxin:-60;offsetyin:bottom;durationin:700;delayin:1200;easingin:easeOutQuart;offsetxout:left;easingout:easeInQuart;parallaxlevel:1;"></div>
			<div class="ls-l" style="top:50px;left:660px;width:7px;height:7px;border-top:1px solid #fff;;border-right:1px solid #fff;;border-bottom:1px solid #fff;;border-left:1px solid #fff;;border-radius:15px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:top;durationin:500;delayin:1300;easingin:easeOutQuart;offsetxout:left;easingout:easeInQuart;parallaxlevel:-1;"></div>
			<div class="ls-l" style="top:425px;left:1140px;width:20px;height:20px;border-top:1px solid #fff;;border-right:1px solid #fff;;border-bottom:1px solid #fff;;border-left:1px solid #fff;;border-radius:15px;white-space: nowrap;" data-ls="offsetxin:-60;offsetyin:bottom;durationin:700;delayin:1400;easingin:easeOutQuart;offsetxout:left;easingout:easeInQuart;parallaxlevel:5;"></div>
			<img class="ls-l" style="top:154px;left:304px;white-space: nowrap;" data-ls="offsetxin:-150;offsetyin:bottom;durationin:1500;delayin:300;easingin:easeOutQuart;rotatein:-190;offsetxout:-150;offsetyout:bottom;durationout:700;easingout:easeInQuart;rotateout:190;parallaxlevel:2;" src="resources/assets/smartlinks/2016/01/Slide5_El2.png" alt=""><img class="ls-l" style="top:350px;left:500px;white-space: nowrap;" data-ls="offsetxin:50;offsetyin:bottom;delayin:700;easingin:easeOutQuart;rotatein:50;rotatexin:50;offsetxout:50;offsetyout:bottom;durationout:700;easingout:easeInQuart;rotateout:-50;parallaxlevel:1;" src="resources/assets/smartlinks/2016/01/Slide5_El1.png" alt="">
			<img class="ls-l" style="top:-60px;left:360px;white-space: nowrap;" data-ls="offsetyin:top;delayin:800;easingin:easeOutQuart;rotatein:-60;rotatexin:-90;offsetxout:80;offsetyout:top;durationout:700;easingout:easeInQuart;rotateout:60;parallaxlevel:1;" src="resources/assets/smartlinks/2016/01/Slide5_El4.png" alt="">
			<img class="ls-l" style="top:265px;left:90px;white-space: nowrap;" data-ls="offsetxin:-600;offsetyin:300;durationin:1500;delayin:500;easingin:easeOutQuart;rotatein:100;offsetxout:-600;offsetyout:300;durationout:700;easingout:easeInQuart;rotateout:-100;parallaxlevel:1;" src="resources/assets/smartlinks/2016/01/Slide5_El5.png" alt="">
			<img class="ls-l" style="top:385px;left:310px;white-space: nowrap;" data-ls="offsetxin:-50;offsetyin:bottom;durationin:800;delayin:800;easingin:easeOutQuart;rotatein:-70;offsetxout:-50;offsetyout:bottom;durationout:500;easingout:easeInQuart;rotateout:70;parallaxlevel:1;" src="resources/assets/smartlinks/2016/01/Slide5_El3.png" alt=""><img class="ls-l" style="top:180px;left:200px;white-space: nowrap;" data-ls="offsetxin:left;offsetyin:50;durationin:3000;delayin:1400;easingin:easeOutQuart;rotatein:-2500;offsetxout:left;offsetyout:50;durationout:700;easingout:easeInQuart;rotateout:1000;parallaxlevel:3;" src="resources/assets/smartlinks/2016/01/Slide5_El6.png" alt="">
			<img class="ls-l" style="top:10px;left:180px;white-space: nowrap;" data-ls="offsetxin:-30;offsetyin:top;durationin:700;delayin:700;easingin:easeOutQuart;rotatein:-40;offsetxout:-30;offsetyout:top;durationout:700;easingout:easeInQuart;rotateout:40;parallaxlevel:1;" src="resources/assets/smartlinks/2016/01/Slide5_El7.png" alt="">
			<img class="ls-l" style="top:-30px;left:40px;white-space: nowrap;" data-ls="offsetxin:left;offsetyin:-300;durationin:1800;delayin:800;easingin:easeOutQuart;rotatein:120;offsetxout:left;offsetyout:-300;durationout:700;easingout:easeInQuart;rotateout:-120;parallaxlevel:1;" src="resources/assets/smartlinks/2016/01/Slide5_El8.png" alt="">
			<img class="ls-l" style="top:290px;left:735px;white-space: nowrap;" data-ls="offsetxin:30;offsetyin:250;durationin:5000;delayin:500;easingin:easeOutQuart;rotatein:-5000;offsetxout:30;offsetyout:250;durationout:700;easingout:easeInQuart;parallaxlevel:1;" src="resources/assets/smartlinks/2016/01/Slide5_El9.png" alt="">
			<img class="ls-l" style="top:330px;left:780px;white-space: nowrap;" data-ls="offsetxin:40;offsetyin:200;durationin:2000;delayin:1700;easingin:easeOutQuart;rotatein:-120;offsetxout:40;offsetyout:200;durationout:700;easingout:easeInQuart;parallaxlevel:2;" src="resources/assets/smartlinks/2016/01/Slide5_El10.png" alt="">
			<div class="ls-l" style="top:61px;left:738px;font-family:helveticaneueultralight;font-size:80px;color:#ffffff;white-space: nowrap;" data-ls="offsetxin:50;offsetyin:top;delayin:800;easingin:easeOutQuart;rotatein:-50;offsetxout:left;offsetyout:-60;durationout:1000;easingout:easeInBack;rotateout:30;parallaxlevel:-3;">Marketing Online</div>
			<div class="ls-l" style="top:155px;left:741px;font-family:helveticaneueultralight;font-size:30px;color:#ffffff;white-space: nowrap;" data-ls="offsetxin:40;offsetyin:top;durationin:1200;delayin:600;easingin:easeOutQuart;rotatein:-10;offsetxout:left;durationout:1000;easingout:easeInBack;rotateout:10;parallaxlevel:-1;">Góp Phần Thành Công Cho Doanh Nghiệp</div>
			<div class="ls-l" style="top:205px;left:799px;font-family:helveticaneueultralight;font-size:30px;color:#ffffff;white-space: nowrap;" data-ls="offsetxin:40;offsetyin:bottom;durationin:1200;delayin:700;easingin:easeOutQuart;rotatein:20;offsetxout:left;offsetyout:30;durationout:1000;easingout:easeInBack;rotateout:-5;parallaxlevel:-1;">Khởi Tạo Chiến Dịch Cùng Smartkinks </div>
			<div class="ls-l" style="top:281px;left:988px;white-space: nowrap;" data-ls="offsetxin:40;offsetyin:bottom;durationin:1100;delayin:800;easingin:easeOutQuart;rotatein:30;offsetxout:left;offsetyout:60;durationout:1000;easingout:easeInBack;rotateout:-15;"><a href="lien-he/index.html" class="button" style="background-color: #723362;">Liên Hệ Báo Giá </a>
			</div>
		</div>


		<div class="ls-slide" data-ls="slidedelay:5300;timeshift:300; transition2d: all;">
			<img class="ls-l" style="top:0px;left:50%;white-space: nowrap;" data-ls="offsetxin:0;easingin:easeInOutSine;offsetxout:0;durationout:800;easingout:easeInOutSine;" src="resources/assets/smartlinks/2016/01/slider_background_3.jpg" alt=""><div class="ls-l" style="top:300px;left:715px;width:8px;height:8px;background:#48afdb;border-radius:10px;white-space: nowrap;" data-ls="offsetxin:-300;offsetyin:30;durationin:2000;delayin:700;easingin:easeOutExpo;offsetxout:left;durationout:2000;easingout:easeInBack;parallaxlevel:1;"></div>
			<div class="ls-l" style="top:370px;left:805px;width:15px;height:15px;background:#48afdb;border-radius:10px;white-space: nowrap;" data-ls="offsetxin:-400;offsetyin:-20;durationin:2000;delayin:700;easingin:easeOutExpo;offsetxout:left;durationout:2000;easingout:easeInBack;parallaxlevel:3;"></div>
			<div class="ls-l" style="top:95px;left:435px;width:3px;height:3px;border-top:1px solid #fff;;border-right:1px solid #fff;;border-bottom:1px solid #fff;;border-left:1px solid #fff;;border-radius:10px;white-space: nowrap;" data-ls="offsetxin:-40;offsetyin:100;durationin:2000;delayin:700;easingin:easeOutExpo;offsetxout:left;durationout:2000;easingout:easeInBack;parallaxlevel:-1;"></div>
			<div class="ls-l" style="top:130px;left:385px;width:7px;height:7px;border-top:1px solid #fff;;border-right:1px solid #fff;;border-bottom:1px solid #fff;;border-left:1px solid #fff;;border-radius:10px;white-space: nowrap;" data-ls="offsetxin:-20;offsetyin:100;durationin:2000;delayin:700;easingin:easeOutExpo;offsetxout:left;durationout:2000;easingout:easeInBack;parallaxlevel:1;"></div>
			<div class="ls-l" style="top:55px;left:305px;width:21px;height:21px;border-top:1px solid #fff;;border-right:1px solid #fff;;border-bottom:1px solid #fff;;border-left:1px solid #fff;;border-radius:11px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:100;durationin:2000;delayin:700;easingin:easeOutExpo;offsetxout:left;durationout:2000;easingout:easeInBack;parallaxlevel:2;"></div>
			<div class="ls-l" style="top:-445px;left:730px;width:500px;height:500px;border-top:1px solid #fff;;border-right:1px solid #fff;;border-bottom:1px solid #fff;;border-left:1px solid #fff;;border-radius:300px;white-space: nowrap;" data-ls="offsetxin:-600;offsetyin:450;durationin:2000;delayin:700;easingin:easeOutExpo;scalexin:0.1;scaleyin:0.1;offsetxout:left;durationout:2000;easingout:easeInBack;parallaxlevel:-12;"></div>
			<div class="ls-l" style="top:175px;left:475px;width:150px;height:150px;border-top:1px solid #fff;;border-right:1px solid #fff;;border-bottom:1px solid #fff;;border-left:1px solid #fff;;border-radius:100px;white-space: nowrap;" data-ls="offsetxin:-80;offsetyin:40;durationin:2000;delayin:700;easingin:easeOutExpo;scalexin:0.5;scaleyin:0.5;offsetxout:left;durationout:2000;easingout:easeInBack;parallaxlevel:-1;"></div>
			<div class="ls-l" style="top:330px;left:660px;width:36px;height:36px;border-top:1px solid #48afdb;;border-right:1px solid #48afdb;;border-bottom:1px solid #48afdb;;border-left:1px solid #48afdb;;border-radius:25px;white-space: nowrap;" data-ls="offsetxin:-60;durationin:2000;delayin:700;easingin:easeOutExpo;scalexin:0.5;scaleyin:0.5;offsetxout:left;durationout:2000;easingout:easeInBack;"></div>
			<div class="ls-l" style="top:63px;left:680px;font-family:helveticaneueultralight;font-size:80px;color:#ffffff;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:bottom;delayin:900;easingin:easeOutQuart;rotatein:20;offsetxout:-400;durationout:2100;easingout:easeInBack;rotateout:30;parallaxlevel:-3;">Google Adwords</div><div class="ls-l" style="top:189px;left:723px;font-family:helveticaneueultralight;font-size:30px;line-height:40px;color:#3b3e4f;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:bottom;delayin:1100;easingin:easeOutQuart;rotatein:20;offsetxout:-400;durationout:2300;easingout:easeInBack;parallaxlevel:-1;">Mang Lại Hiệu Quả Cho Doanh Nghiệp</div><div class="ls-l" style="top:236px;left:731px;font-family:helveticaneueultralight;font-size:30px;line-height:40px;color:#3b3e4f;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:bottom;delayin:1300;easingin:easeOutQuart;rotatein:20;offsetxout:-400;durationout:2500;easingout:easeInBack;rotateout:-20;parallaxlevel:-1;">Khởi Tạo Chiến Dịch Cùng Smartlinks</div>
			<div class="ls-l" style="top:294px;left:773px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:-50;durationin:1500;delayin:1400;easingin:easeOutBounce;rotatein:-3;offsetxout:-200;durationout:2600;easingout:easeInBack;rotateout:-1;"><a href="dich-vu/google-adwords/index.html" class="button" style="background-color: #3a8a9a;">Chi Tiết</a></div>
			<div class="ls-l" style="top:293px;left:1003px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:-50;durationin:1500;delayin:1500;easingin:easeOutBounce;rotatein:-2;offsetxout:-200;durationout:2900;easingout:easeInBack;rotateout:-4;"><a href="lien-he/index.html" class="button" style="background-color: #71c084;">Liên Hệ Báo Giá</a>
			</div>
			<img class="ls-l" style="top:39px;left:87px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:-200;durationin:1500;delayin:400;easingin:easeOutBounce;skewxin:-2;skewyin:2;offsetxout:left;durationout:2000;easingout:easeInBack;skewxout:20;parallaxlevel:1;" src="resources/assets/smartlinks/2016/01/gads6.png" alt="">
		</div>


		<div class="ls-slide" data-ls="slidedelay:5500;timeshift:500; transition2d: all;">
			<img class="ls-l" style="top:50%;left:50%;white-space: nowrap;" data-ls="offsetxin:0;durationin:2000;easingin:easeInOutSine;offsetxout:0;" src="resources/assets/smartlinks/2016/01/slider_background_4.jpg" alt=""><img class="ls-l" style="top:1px;left:777px;white-space: nowrap;" data-ls="offsetxin:250;durationin:1500;easingin:easeOutQuart;scalexin:0.1;scaleyin:0.1;offsetxout:-600;offsetyout:250;durationout:2000;easingout:easeInQuart;scalexout:2;scaleyout:2;parallaxlevel:-1;" src="resources/assets/smartlinks/2016/01/facebook1.png" alt="">
			<div class="ls-l" style="top:75px;left:1020px;width:28px;height:28px;background:#fff;border-radius:25px;white-space: nowrap;" data-ls="offsetxin:-80;offsetyin:120;delayin:700;easingin:easeOutQuart;scalexin:0.5;scaleyin:0.5;offsetxout:-650;offsetyout:-200;durationout:1000;easingout:easeInQuart;"></div>
			<div class="ls-l" style="top:135px;left:1015px;width:6px;height:6px;background:#fff;border-radius:25px;white-space: nowrap;" data-ls="offsetxin:-80;offsetyin:60;durationin:700;delayin:700;easingin:easeOutQuart;offsetxout:-630;offsetyout:-200;durationout:1000;easingout:easeInQuart;parallaxlevel:-1;"></div>
			<div class="ls-l" style="top:115px;left:785px;width:17px;height:17px;background:#fff;border-radius:25px;white-space: nowrap;" data-ls="offsetxin:120;offsetyin:50;delayin:700;easingin:easeOutQuart;scalexin:0.7;scaleyin:0.7;offsetxout:-640;offsetyout:-200;durationout:1000;easingout:easeInQuart;parallaxlevel:1;"></div>
			<div class="ls-l" style="top:90px;left:870px;width:7px;height:7px;background:#48afdb;border-radius:25px;white-space: nowrap;" data-ls="offsetxin:50;offsetyin:70;durationin:800;delayin:700;easingin:easeOutQuart;offsetxout:-620;offsetyout:-200;durationout:1000;easingout:easeInQuart;parallaxlevel:-1;"></div>
			<div class="ls-l" style="top:35px;left:1155px;width:7px;height:7px;border-top:1px solid #3b3e4f;;border-right:1px solid #3b3e4f;border-bottom:1px solid #3b3e4f;;border-left:1px solid #3b3e4f;;border-radius:25px;white-space: nowrap;" data-ls="offsetxin:-190;offsetyin:200;durationin:1500;delayin:700;easingin:easeOutQuart;offsetxout:-630;offsetyout:-150;durationout:1000;easingout:easeInQuart;parallaxlevel:-3;"></div>
			<div class="ls-l" style="top:110px;left:1110px;width:21px;height:21px;background:#60dbc4;border-radius:25px;white-space: nowrap;" data-ls="offsetxin:-100;offsetyin:80;durationin:1500;delayin:700;easingin:easeOutQuart;offsetxout:-610;offsetyout:-250;durationout:1000;easingout:easeInQuart;parallaxlevel:1;"></div>
			<div class="ls-l" style="top:22px;left:822px;width:13px;height:13px;background:#60dbc4;border-radius:25px;white-space: nowrap;" data-ls="offsetxin:130;offsetyin:150;durationin:1700;delayin:700;easingin:easeOutQuart;offsetxout:-640;offsetyout:-300;durationout:1000;easingout:easeInQuart;parallaxlevel:2;"></div>
			<div class="ls-l" style="top:15px;left:655px;width:43px;height:43px;border-top:1px solid #48afdb;;border-right:1px solid #48afdb;;border-bottom:1px solid #48afdb;;border-left:1px solid #48afdb;;border-radius:25px;white-space: nowrap;" data-ls="offsetxin:230;offsetyin:140;durationin:2000;delayin:700;easingin:easeOutQuart;scalexin:0.5;scaleyin:0.5;offsetxout:-630;offsetyout:-350;durationout:1000;easingout:easeInQuart;parallaxlevel:5;"></div>
			<img class="ls-l" style="top:341px;left:1150px;white-space: nowrap;" data-ls="offsetxin:700;offsetyin:200;durationin:1500;easingin:easeOutBack;fadein:false;rotatein:30;offsetxout:700;offsetyout:200;durationout:1000;easingout:easeInQuart;rotateout:30;parallaxlevel:-2;" src="resources/assets/smartlinks/2016/01/cursor.png" alt="">
			<div class="ls-l" style="top:45px;left:52px;font-family:helveticaneueultralight;font-size:80px;color:#48afdb;white-space: nowrap;" data-ls="offsetxin:130;offsetyin:-150;durationin:2000;delayin:1000;easingin:easeOutElastic;rotatein:45;rotateyin:60;offsetxout:left;offsetyout:-200;durationout:2000;easingout:easeInQuart;rotateout:-35;rotateyout:-60;scalexout:2;scaleyout:2;parallaxlevel:3;">Facebook Ads</div>
			<div class="ls-l" style="top:165px;left:48px;font-family:helveticaneueultralight;font-size:80px;color:#9bca4a;white-space: nowrap;" data-ls="offsetxin:170;offsetyin:-100;durationin:2000;delayin:1100;easingin:easeOutElastic;rotatein:35;rotateyin:60;offsetxout:left;offsetyout:-150;durationout:2300;easingout:easeInQuart;rotateout:-25;rotateyout:-60;scalexout:1.7;scaleyout:1.7;parallaxlevel:2;">Miền Đất Hứa</div>
			<div class="ls-l" style="top:335px;left:48px;font-family:helveticaneueultralight;font-size:30px;color:#3b3e4f;white-space: nowrap;" data-ls="offsetxin:170;offsetyin:-50;durationin:2000;delayin:1200;easingin:easeOutElastic;rotatein:25;rotateyin:60;offsetxout:left;offsetyout:-100;durationout:2600;easingout:easeInQuart;rotateout:-15;rotateyout:-60;scalexout:1.3;scaleyout:1.3;parallaxlevel:1;">Khởi Tạo Chiến Dịch Cùng Smartlinks</div>
			<div class="ls-l" style="top:284px;left:50px;font-family:helveticaneueultralight;font-size:30px;color:#3b3e4f;white-space: nowrap;" data-ls="offsetxin:140;offsetyin:-20;durationin:2000;delayin:1300;easingin:easeOutElastic;rotatein:15;rotateyin:60;offsetxout:left;offsetyout:-50;durationout:2900;easingout:easeInQuart;rotateout:-5;rotateyout:-60;scalexout:1.2;scaleyout:1.2;parallaxlevel:1;">Là Mảnh Đất Quảng Cáo Màu Mỡ Dành Cho Doanh Nghiệp</div>
			<div class="ls-l" style="top:368px;left:48px;width:;height:;padding-top:;padding-right:;padding-bottom:;padding-left:;border-top:;border-right:;border-bottom:;border-left:;font-family:;font-size:;line-height:;color:;background:;border-radius:;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:-80;durationin:1500;delayin:1100;easingin:easeOutElastic;rotatein:-10;offsetyout:-1000;durationout:2400;easingout:easeInQuad;rotateout:20;rotateyout:200;"><a href="dich-vu/facebook-ads/index.html" class="button" style="background-color: #fa566e;">Chi Tiết</a>
			</div>
		</div>


		<div class="ls-slide" data-ls="slidedelay:5300;timeshift:300; transition2d: all;">
			<img class="ls-l" style="top:50%;left:50%;white-space: nowrap;" data-ls="offsetxin:0;durationin:1500;easingin:easeInOutSine;offsetxout:0;durationout:1000;easingout:easeInOutSine;" src="resources/assets/smartlinks/2016/01/slider_background_7.jpg" alt="">
			<img class="ls-l" style="top:167px;left:-80px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:bottom;delayin:900;easingin:easeOutQuart;fadein:false;offsetxout:0;offsetyout:bottom;durationout:500;easingout:easeInQuart;rotateyout:-50;parallaxlevel:1;" src="resources/assets/smartlinks/2016/01/tablet_mockup.png" alt="">
			<img class="ls-l" style="top:240px;left:140px;white-space: nowrap;" data-ls="offsetxin:0;delayin:1600;easingin:easeOutQuart;offsetxout:0;offsetyout:100;durationout:100;easingout:easeInOutSine;parallaxlevel:2;" src="resources/assets/smartlinks/2016/01/phone_shadow.png" alt="">
			<img class="ls-l" style="top:165px;left:125px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:top;durationin:1400;delayin:1100;easingin:easeOutQuart;fadein:false;offsetxout:0;offsetyout:top;durationout:700;easingout:easeInQuart;fadeout:false;rotateyout:500;skewxout:50;parallaxlevel:3;" src="resources/assets/smartlinks/2016/01/phone_mockup.png" alt=""><img class="ls-l" style="top:-30px;left:-35px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:top;delayin:1200;easingin:easeOutQuart;offsetxout:0;offsetyout:top;durationout:700;easingout:easeInQuart;parallaxlevel:1;" src="resources/assets/smartlinks/2016/01/corner_light_2.png" alt="">
			<img class="ls-l" style="top:415px;left:795px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:bottom;durationin:700;delayin:1400;easingin:easeOutQuart;fadein:false;offsetxout:0;offsetyout:bottom;easingout:easeInQuart;parallaxlevel:-1;" src="resources/assets/smartlinks/2016/01/corner_light_1.png" alt="">
			<div class="ls-l" style="top:33px;left:552px;width:13px;height:13px;border-top:1px solid #fff;;border-right:1px solid #fff;;border-bottom:1px solid #fff;;border-left:1px solid #fff;;border-radius:11px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:bottom;delayin:500;easingin:easeOutQuart;fadein:false;offsetxout:0;offsetyout:top;durationout:700;easingout:easeInQuart;parallaxlevel:-2;"></div>
			<div class="ls-l" style="top:120px;left:485px;width:4px;height:4px;border-top:1px solid #fff;;border-right:1px solid #fff;;border-bottom:1px solid #fff;;border-left:1px solid #fff;;border-radius:11px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:bottom;delayin:600;easingin:easeOutQuart;fadein:false;offsetxout:0;offsetyout:top;durationout:700;easingout:easeInQuart;parallaxlevel:-1;"></div>
			<div class="ls-l" style="top:325px;left:755px;width:4px;height:4px;border-top:1px solid #fff;;border-right:1px solid #fff;;border-bottom:1px solid #fff;;border-left:1px solid #fff;;border-radius:11px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:bottom;delayin:700;easingin:easeOutQuart;fadein:false;offsetxout:0;offsetyout:top;durationout:700;easingout:easeInQuart;parallaxlevel:-1;"></div>
			<div class="ls-l" style="top:390px;left:775px;width:25px;height:25px;border-top:1px solid #fff;;border-right:1px solid #fff;;border-bottom:1px solid #fff;;border-left:1px solid #fff;;border-radius:15px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:bottom;delayin:800;easingin:easeOutQuart;fadein:false;offsetxout:0;offsetyout:top;durationout:700;easingout:easeInQuart;parallaxlevel:-7;"></div>
			<div class="ls-l" style="top:93px;left:450px;width:8px;height:8px;background:#48afdb;border-radius:15px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:bottom;delayin:900;easingin:easeOutQuart;fadein:false;offsetxout:0;offsetyout:top;durationout:700;easingout:easeInQuart;parallaxlevel:1;"></div>
			<div class="ls-l" style="top:335px;left:675px;width:13px;height:13px;background:#60dbc4;border-radius:15px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:bottom;delayin:1000;easingin:easeOutQuart;fadein:false;offsetxout:0;offsetyout:top;durationout:700;easingout:easeInQuart;parallaxlevel:-2;"></div>
			<div class="ls-l" style="top:33px;left:658px;font-family:helveticaneueultralight;font-size:80px;color:#ffffff;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:bottom;delayin:400;easingin:easeOutQuart;rotatein:5;offsetxout:0;offsetyout:-1000;durationout:30;easingout:easeInQuart;rotateout:40;rotateyout:600;parallaxlevel:-3;">Thiết Kế Website</div>
			<div class="ls-l" style="top:140px;left:708px;font-family:helveticaneueultralight;font-size:70px;color:#ffffff;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:bottom;delayin:500;easingin:easeOutQuart;rotatein:10;offsetxout:0;offsetyout:-1000;durationout:300;easingout:easeInQuart;rotateout:35;rotateyout:500;parallaxlevel:-2;"><span style="color: #71dfca; background-color: rgba(58, 83, 112, 0.6);padding: 0 20px;">Chuyên Nghiệp </span>
			</div>
			<div class="ls-l" style="top:243px;left:714px;font-family:helveticaneueultralight;font-size:30px;color:#ffffff;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:bottom;delayin:600;easingin:easeOutQuart;rotatein:15;offsetxout:0;offsetyout:-1000;durationout:600;easingout:easeInQuart;rotateout:30;rotateyout:400;parallaxlevel:-1;">Giao Diện Hiện Đại Tích Hợp Di Động</div>
			<div class="ls-l" style="top:288px;left:724px;font-family:helveticaneueultralight;font-size:30px;color:#ffffff;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:bottom;delayin:700;easingin:easeOutQuart;rotatein:20;offsetxout:0;offsetyout:-1000;durationout:1200;easingout:easeInQuart;rotateout:25;rotateyout:300;parallaxlevel:-1;">Chi Phí Hợp Lý - Bảo Hành Trọn Đời</div>
			<div class="ls-l" style="top:327px;left:1006px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:-80;durationin:1500;delayin:1100;easingin:easeOutElastic;rotatein:-10;offsetxout:0;offsetyout:-1000;durationout:2400;easingout:easeInQuart;rotateout:20;rotateyout:200;"><a href="dich-vu/thiet-ke-web/index.html" class="button" style="background-color: #fa566e;">Chi Tiết</a>
			</div>
		</div>


		<div class="ls-slide" data-ls="slidedelay:5300;timeshift:300; transition2d: all;">
			<img class="ls-l" style="top:50%;left:50%;white-space: nowrap;" data-ls="offsetxin:0;durationin:1500;easingin:easeInOutSine;offsetxout:0;durationout:1500;easingout:easeInOutSine;" src="resources/assets/smartlinks/2016/01/slider_background_6.jpg" alt="">
			<img class="ls-l" style="top:260px;left:490px;white-space: nowrap;" data-ls="offsetxin:-80;offsetyin:-40;durationin:1500;delayin:1300;easingin:easeOutQuart;offsetyout:-40;durationout:500;parallaxlevel:-1;" src="resources/assets/smartlinks/2016/01/screen_shadow.png" alt=""><img class="ls-l" style="top:-90px;left:830px;white-space: nowrap;" data-ls="offsetxin:-80;offsetyin:-80;durationin:1500;delayin:1300;easingin:easeOutQuart;offsetyout:-80;durationout:500;parallaxlevel:-1;" src="resources/assets/smartlinks/2016/01/screen_shadow.png" alt="">
			<img class="ls-l" style="top:180px;left:437px;white-space: nowrap;" data-ls="offsetxin:-295;offsetyin:295;durationin:1500;delayin:800;easingin:easeOutQuart;fadein:false;offsetxout:-295;offsetyout:295;durationout:500;easingout:easeInQuart;fadeout:false;parallaxlevel:-2;" src="resources/assets/smartlinks/2016/01/screen_11.png" alt="">
			<img class="ls-l" style="top:-12px;left:785px;white-space: nowrap;" data-ls="offsetxin:260;offsetyin:-260;durationin:1500;delayin:800;easingin:easeOutQuart;fadein:false;offsetxout:260;offsetyout:-260;durationout:500;easingout:easeInQuart;fadeout:false;parallaxlevel:-2;" src="resources/assets/smartlinks/2016/01/screen_2222.png" alt="">
			<img class="ls-l" style="top:376px;left:910px;white-space: nowrap;" data-ls="offsetxin:-85;offsetyin:85;durationin:1500;delayin:800;easingin:easeOutQuart;fadein:false;offsetxout:-85;offsetyout:85;durationout:500;easingout:easeInQuart;fadeout:false;parallaxlevel:1;" src="resources/assets/smartlinks/2016/01/corner_dark.png" alt="">
			<img class="ls-l" style="top:-10px;left:437px;white-space: nowrap;" data-ls="offsetxin:63;offsetyin:-63;durationin:1500;delayin:800;easingin:easeOutQuart;fadein:false;offsetxout:63;offsetyout:-63;durationout:500;easingout:easeInQuart;fadeout:false;parallaxlevel:1;" src="resources/assets/smartlinks/2016/01/corner_dark_2.png" alt="">
			<div class="ls-l" style="top:40px;left:690px;width:7px;height:7px;border-top:1px solid #3b3e4f;;border-right:1px solid #3b3e4f;;border-bottom:1px solid #3b3e4f;;border-left:1px solid #3b3e4f;;border-radius:13px;white-space: nowrap;" data-ls="offsetxin:-438;offsetyin:438;delayin:900;easingin:easeOutQuart;fadein:false;offsetxout:50;offsetyout:-50;durationout:800;easingout:easeInBack;fadeout:false;parallaxlevel:3;"></div>
			<div class="ls-l" style="top:375px;left:1147px;width:25px;height:25px;border-top:1px solid #3b3e4f;;border-right:1px solid #3b3e4f;;border-bottom:1px solid #3b3e4f;;border-left:1px solid #3b3e4f;;border-radius:13px;white-space: nowrap;" data-ls="offsetxin:-120;offsetyin:120;delayin:950;easingin:easeOutQuart;fadein:false;offsetxout:430;offsetyout:-430;durationout:800;easingout:easeInBack;fadeout:false;parallaxlevel:7;"></div>
			<div class="ls-l" style="top:180px;left:1180px;width:18px;height:18px;background:#fff;border-radius:9px;white-space: nowrap;" data-ls="offsetxin:-296;offsetyin:296;delayin:1000;easingin:easeOutQuart;fadein:false;offsetxout:250;offsetyout:-250;durationout:800;easingout:easeInBack;fadeout:false;parallaxlevel:5;"></div>
			<div class="ls-l" style="top:47px;left:755px;width:14px;height:14px;background:#60dbc4;border-radius:8px;white-space: nowrap;" data-ls="offsetxin:-433;offsetyin:433;delayin:1050;easingin:easeOutQuart;fadein:false;offsetxout:60;offsetyout:-60;durationout:800;easingout:easeInBack;fadeout:false;parallaxlevel:4;"></div>
			<div class="ls-l" style="top:140px;left:720px;width:6px;height:6px;background:#ff5373;border-radius:15px;white-space: nowrap;" data-ls="offsetxin:-340;offsetyin:340;delayin:1100;easingin:easeOutQuart;fadein:false;offsetxout:160;offsetyout:-160;durationout:800;easingout:easeInBack;fadeout:false;parallaxlevel:1;"></div>
			<div class="ls-l" style="top:315px;left:1090px;width:10px;height:10px;background:#ff5373;border-radius:8px;white-space: nowrap;" data-ls="offsetxin:-170;offsetyin:170;delayin:1150;easingin:easeOutQuart;fadein:false;offsetxout:350;offsetyout:-350;durationout:800;easingout:easeInBack;fadeout:false;parallaxlevel:3;"></div>
			<div class="ls-l" style="top:90px;left:43px;font-family:helveticaneueultralight;font-size:85px;white-space: nowrap;" data-ls="offsetxin:400;offsetyin:-100;durationin:2000;delayin:300;easingin:easeOutElastic;rotatein:-50;offsetxout:left;offsetyout:-200;durationout:1000;easingout:easeInBack;rotateout:50;parallaxlevel:-4;">Thiết Kế<span style="color: #ff5373;"> Logo</span>
			</div>
			<div class="ls-l" style="top:210px;left:52px;font-family:helveticaneueultralight;font-size:30px;color:#3b3e4f;white-space: nowrap;" data-ls="offsetxin:400;offsetyin:-50;durationin:2000;delayin:400;easingin:easeOutElastic;rotatein:-25;offsetxout:left;offsetyout:-100;durationout:1000;easingout:easeInBack;rotateout:25;parallaxlevel:-3;">Thiết Kế Logo  <a href="http://themeforest.net/user/Kontramax?ref=kontramax" target="_blank" style="color: #ff5373; text-decoration: none;">Thương Hiệu</a>!</div>
			<div class="ls-l" style="top:250px;left:52px;font-family:helveticaneueultralight;font-size:30px;color:#3b3e4f;white-space: nowrap;" data-ls="offsetxin:400;durationin:2000;delayin:500;easingin:easeOutElastic;rotatein:-5;offsetxout:left;durationout:1000;easingout:easeInBack;rotateout:5;parallaxlevel:-2;">Sáng Tạo Trong Từng Ý Tưởng</div>
			<div class="ls-l" style="top:290px;left:52px;font-family:helveticaneueultralight;font-size:30px;color:#3b3e4f;white-space: nowrap;" data-ls="offsetxin:400;offsetyin:50;durationin:2000;delayin:600;easingin:easeOutElastic;rotatein:15;offsetxout:left;offsetyout:100;durationout:1000;easingout:easeInBack;rotateout:-15;parallaxlevel:-1;">Mang Nét Riêng Cho Doanh Nghiệp</div>
			<div class="ls-l" style="top:324px;left:54px;white-space: nowrap;" data-ls="offsetxin:400;offsetyin:100;durationin:2000;delayin:700;easingin:easeOutElastic;rotatein:35;offsetxout:left;offsetyout:200;durationout:1000;easingout:easeInBack;rotateout:-35;"><a href="dich-vu/thiet-ke-logo/index.html" class="button" style="background-color: #3a5370;">Chi Tiết</a>
			</div>
		</div>
	</div>												
</div>